# Configuration file
# key = value
server:
  port: 8081

spring:
  # Konfiguration der Datenbank.
  datasource:
    #example for not "in memory"
    # url=jdbc:h2:file:/data/demo 
    url: jdbc:postgresql://localhost:5432/microprofile
    username: postgres
    password: admin
#  jpa:
#    #database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
#    hibernate:
#      ddl-auto: ${DDL_AUTO:validate}
      
config:
  service:
    rest:
      url: https://jsonplaceholder.typicode.com/