# Configuration file
# key = value

quarkus:
  datasource:
    url: jdbc:postgresql://localhost:5432/microprofile
    driver: org.postgresql.Driver
    username: postgres
    password: admin
    
  hibernate-orm:
    database:
      generation: drop-and-create
      
config:
  service:
    rest:
      url: https://jsonplaceholder.typicode.com/